# Generated by Django 2.2 on 2020-03-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HalfHourFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('asset_id', models.CharField(max_length=15)),
                ('asset_power', models.FloatField()),
                ('carbon_intensity', models.FloatField()),
            ],
        ),
    ]
