# Generated by Django 3.0.4 on 2020-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint_calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halfhourfootprint',
            name='time',
        ),
        migrations.AddField(
            model_name='halfhourfootprint',
            name='duration',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halfhourfootprint',
            name='asset_id',
            field=models.CharField(max_length=45),
        ),
    ]
