# Generated by Django 3.0.4 on 2020-03-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint_calc', '0002_auto_20200310_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halfhourfootprint',
            old_name='duration',
            new_name='time_period',
        ),
    ]
