# Generated by Django 3.0.4 on 2020-03-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint_calc', '0003_auto_20200311_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhourfootprint',
            name='asset_id',
            field=models.CharField(max_length=15),
        ),
    ]
